version: '3.8'
services:
  php:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/symfony
    networks:
      - app_net
    ports:
      - "9000:9000"  # Port pour PHP-FPM
      - "9003:9003"  # Port pour Xdebug
    depends_on:
      - postgres
#    command: bash -c "composer install"
#    command: bash -c "composer install && php bin/console doctrine:migrations:migrate --no-interaction"

  nginx:
    image: nginx:latest
    volumes:
      - .:/var/www/symfony
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - php
    networks:
      - app_net

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: socialNetwork
      POSTGRES_USER: red
      POSTGRES_PASSWORD: red12345
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_net

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: user@example.com
      PGADMIN_DEFAULT_PASSWORD: adminpassword
    ports:
      - "8081:80"
    networks:
      - app_net

networks:
  app_net:
    driver: bridge

volumes:
  postgres_data: